site_name: AI Developer Toolkit
site_description: Comprehensive toolkit for rapidly building AI solutions
site_author: AI Toolkit Team

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started/getting-started.md
  - Architecture:
    - Overview: architecture/overview.md

plugins:
  - search